worker_processes auto;

events {
    worker_connections 1024;
}

http {
    lua_package_path "/usr/local/openresty/nginx/lua/redis_push.lua;;";
    include       mime.types;
    default_type  application/octet-stream;

    # Custom log format to print requests to console
    log_format watchlog '$remote_addr - $time_local '
                    '"$request" '
                    'Range="$http_range" '
                    'Cache="$upstream_cache_status"';

    access_log /dev/stdout watchlog;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;

    # FIFO caching (Evicts old videos when full)
    proxy_cache_path /var/cache/nginx/video_cache levels=1:2 keys_zone=video_cache:100m inactive=10m max_size=5g use_temp_path=off;

    server {
        listen 8081;
        server_name localhost;

        location /videos/ {
        access_by_lua_file /usr/local/openresty/nginx/lua/redis_push.lua;
        proxy_pass http://192.168.1.8:8080/;
        proxy_cache video_cache;
        proxy_cache_key "$uri$http_range";  # Cache each chunk separately
        proxy_cache_valid 200 206 10m;  # Cache both full responses (200) and partial content (206)
        proxy_cache_min_uses 1;
        proxy_cache_bypass $arg_new_video;
        proxy_no_cache $arg_new_video;

        proxy_cache_lock on;  # Prevents multiple clients from requesting the same chunk simultaneously
        proxy_cache_lock_timeout 5s;  

        proxy_set_header Connection "";
        proxy_ignore_headers "Cache-Control" "Expires";
        proxy_set_header Range $http_range;  # Enable byte-range requests
        proxy_set_header If-Range $http_if_range;
        proxy_pass_request_headers on;  

        add_header X-Cache-Status $upstream_cache_status always;



         body_filter_by_lua_block {
                local chunk = ngx.arg[1]
                local redis_key = ngx.ctx.redis_key
                if redis_key and chunk then
                    local redis = require "resty.redis"
                    local red = redis:new()
                    red:set_timeout(1000)
                    local ok, err = red:connect("192.168.1.8", 6379)
                    if ok then
                        red:auth("default", "user")
                        red:set(redis_key, chunk)
                    end
                end
            }
    }
    }
}
