apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
             command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
        - name: redis-config-volume
          hostPath:
            path: ./redis.conf  # Path on your local machine
            type: File
