version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass user

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=user

  flask:
    build: ./app
    ports:
      - "8080:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=user

  nginx:
    build: ./nginx
    ports:
      - "8081:8081"
    depends_on:
      - flask
